use crate::types::DnsPreset;

pub fn get_default_presets() -> Vec<DnsPreset> {
    vec![
        // Gaming DNS
        DnsPreset {
            id: "xbox-dns".to_string(),
            name: "Xbox DNS".to_string(),
            description: "Оптимизированные DNS для Xbox и игр с поддержкой DoH".to_string(),
            category: "gaming".to_string(),
            servers_ipv4: vec![
                "176.99.11.77".to_string(),
                "80.78.247.254".to_string(),
            ],
            servers_ipv6: vec![
                "2a00:f940:2:4:2::5d1b".to_string(),
                "2a00:f940:2:4:2::21ed".to_string(),
            ],
            doh_template: Some("https://xbox-dns.ru/dns-query".to_string()),
            dot_hostname: Some("xbox-dns.ru".to_string()),
            supports_doh: true,
            supports_dot: true,
            icon: "🎮".to_string(),
            color: "#8b5cf6".to_string(),
            website: Some("https://xbox-dns.ru".to_string()),
        },
        DnsPreset {
            id: "comss-one".to_string(),
            name: "Comss.one DNS".to_string(),
            description: "Быстрый безопасный DNS с блокировкой рекламы, трекеров, фишинга + доступ к ИИ-сервисам и низким пингом для игр".to_string(),
            category: "gaming".to_string(),
            servers_ipv4: vec![
                "83.220.169.155".to_string(),
                "212.109.195.93".to_string(),
            ],
            servers_ipv6: vec![],
            doh_template: Some("https://dns.comss.one/dns-query".to_string()),
            dot_hostname: Some("dns.comss.one".to_string()),
            supports_doh: true,
            supports_dot: true,
            icon: "🛡️".to_string(),
            color: "#10b981".to_string(),
            website: Some("https://comss.one".to_string()),
        },
        DnsPreset {
            id: "control-d-gaming".to_string(),
            name: "Control D Gaming".to_string(),
            description: "DNS оптимизированный для геймеров".to_string(),
            category: "gaming".to_string(),
            servers_ipv4: vec![
                "76.76.2.35".to_string(),
                "76.76.10.35".to_string(),
            ],
            servers_ipv6: vec![
                "2606:1a40::35".to_string(),
                "2606:1a40:1::35".to_string(),
            ],
            doh_template: Some("https://gaming.controld.com/dns-query".to_string()),
            dot_hostname: Some("gaming.controld.com".to_string()),
            supports_doh: true,
            supports_dot: true,
            icon: "🎯".to_string(),
            color: "#8b5cf6".to_string(),
            website: Some("https://controld.com".to_string()),
        },
        
        // Public DNS
        DnsPreset {
            id: "google".to_string(),
            name: "Google DNS".to_string(),
            description: "Быстрые и надежные DNS от Google с DoH".to_string(),
            category: "public".to_string(),
            servers_ipv4: vec!["8.8.8.8".to_string(), "8.8.4.4".to_string()],
            servers_ipv6: vec![
                "2001:4860:4860::8888".to_string(),
                "2001:4860:4860::8844".to_string(),
            ],
            doh_template: Some("https://dns.google/dns-query".to_string()),
            dot_hostname: Some("dns.google".to_string()),
            supports_doh: true,
            supports_dot: true,
            icon: "🌐".to_string(),
            color: "#4285f4".to_string(),
            website: Some("https://developers.google.com/speed/public-dns".to_string()),
        },
        DnsPreset {
            id: "opendns".to_string(),
            name: "OpenDNS".to_string(),
            description: "Популярный DNS с функциями безопасности".to_string(),
            category: "public".to_string(),
            servers_ipv4: vec!["208.67.222.222".to_string(), "208.67.220.220".to_string()],
            servers_ipv6: vec![
                "2620:119:35::35".to_string(),
                "2620:119:53::53".to_string(),
            ],
            doh_template: Some("https://doh.opendns.com/dns-query".to_string()),
            dot_hostname: Some("dns.opendns.com".to_string()),
            supports_doh: true,
            supports_dot: true,
            icon: "🌍".to_string(),
            color: "#ff6600".to_string(),
            website: Some("https://www.opendns.com".to_string()),
        },
        DnsPreset {
            id: "yandex-basic".to_string(),
            name: "Яндекс.DNS Базовый".to_string(),
            description: "Быстрый DNS от Яндекса".to_string(),
            category: "public".to_string(),
            servers_ipv4: vec!["77.88.8.8".to_string(), "77.88.8.1".to_string()],
            servers_ipv6: vec![
                "2a02:6b8::feed:0ff".to_string(),
                "2a02:6b8:0:1::feed:0ff".to_string(),
            ],
            doh_template: None,
            dot_hostname: Some("common.dot.dns.yandex.net".to_string()),
            supports_doh: false,
            supports_dot: true,
            icon: "🇷🇺".to_string(),
            color: "#fc3f1d".to_string(),
            website: Some("https://dns.yandex.ru".to_string()),
        },
        DnsPreset {
            id: "level3".to_string(),
            name: "Level3".to_string(),
            description: "Стабильные публичные DNS".to_string(),
            category: "public".to_string(),
            servers_ipv4: vec!["209.244.0.3".to_string(), "209.244.0.4".to_string()],
            servers_ipv6: vec![],
            doh_template: None,
            dot_hostname: None,
            supports_doh: false,
            supports_dot: false,
            icon: "🌐".to_string(),
            color: "#718096".to_string(),
            website: Some("https://www.lumen.com".to_string()),
        },
        DnsPreset {
            id: "verisign".to_string(),
            name: "Verisign".to_string(),
            description: "Стабильный и безопасный DNS".to_string(),
            category: "public".to_string(),
            servers_ipv4: vec!["64.6.64.6".to_string(), "64.6.65.6".to_string()],
            servers_ipv6: vec![
                "2620:74:1b::1:1".to_string(),
                "2620:74:1c::2:2".to_string(),
            ],
            doh_template: None,
            dot_hostname: None,
            supports_doh: false,
            supports_dot: false,
            icon: "✅".to_string(),
            color: "#10b981".to_string(),
            website: Some("https://www.verisign.com/en_US/security-services/public-dns/index.xhtml".to_string()),
        },
        DnsPreset {
            id: "alternate-dns".to_string(),
            name: "Alternate DNS".to_string(),
            description: "Быстрый публичный DNS".to_string(),
            category: "public".to_string(),
            servers_ipv4: vec!["76.76.19.19".to_string(), "76.223.122.150".to_string()],
            servers_ipv6: vec![
                "2602:fcbc::ad".to_string(),
                "2602:fcbc:2::ad".to_string(),
            ],
            doh_template: None,
            dot_hostname: None,
            supports_doh: false,
            supports_dot: false,
            icon: "🔄".to_string(),
            color: "#667eea".to_string(),
            website: Some("https://alternate-dns.com".to_string()),
        },
        
        // Privacy DNS
        DnsPreset {
            id: "cloudflare".to_string(),
            name: "Cloudflare DNS".to_string(),
            description: "Один из самых быстрых DNS с фокусом на приватность".to_string(),
            category: "privacy".to_string(),
            servers_ipv4: vec!["1.1.1.1".to_string(), "1.0.0.1".to_string()],
            servers_ipv6: vec![
                "2606:4700:4700::1111".to_string(),
                "2606:4700:4700::1001".to_string(),
            ],
            doh_template: Some("https://cloudflare-dns.com/dns-query".to_string()),
            dot_hostname: Some("cloudflare-dns.com".to_string()),
            supports_doh: true,
            supports_dot: true,
            icon: "☁️".to_string(),
            color: "#f6821f".to_string(),
            website: Some("https://1.1.1.1".to_string()),
        },
        DnsPreset {
            id: "nextdns".to_string(),
            name: "NextDNS".to_string(),
            description: "Настраиваемый приватный DNS с блокировкой".to_string(),
            category: "privacy".to_string(),
            servers_ipv4: vec!["45.90.28.0".to_string(), "45.90.30.0".to_string()],
            servers_ipv6: vec![
                "2a07:a8c0::".to_string(),
                "2a07:a8c1::".to_string(),
            ],
            doh_template: Some("https://dns.nextdns.io/dns-query".to_string()),
            dot_hostname: Some("dns.nextdns.io".to_string()),
            supports_doh: true,
            supports_dot: true,
            icon: "🔐".to_string(),
            color: "#3b82f6".to_string(),
            website: Some("https://nextdns.io".to_string()),
        },
        DnsPreset {
            id: "mullvad-dns".to_string(),
            name: "Mullvad DNS".to_string(),
            description: "Приватный DNS от Mullvad VPN".to_string(),
            category: "privacy".to_string(),
            servers_ipv4: vec!["194.242.2.2".to_string(), "193.19.108.2".to_string()],
            servers_ipv6: vec![
                "2a07:e340::2".to_string(),
                "2001:67c:27e4::2".to_string(),
            ],
            doh_template: Some("https://dns.mullvad.net/dns-query".to_string()),
            dot_hostname: Some("dns.mullvad.net".to_string()),
            supports_doh: true,
            supports_dot: true,
            icon: "🔒".to_string(),
            color: "#294d73".to_string(),
            website: Some("https://mullvad.net/en/help/dns-over-https-and-dns-over-tls".to_string()),
        },
        DnsPreset {
            id: "privacy-first".to_string(),
            name: "Privacy First DNS".to_string(),
            description: "Фокус на приватность и анонимность".to_string(),
            category: "privacy".to_string(),
            servers_ipv4: vec!["91.239.100.100".to_string(), "89.233.43.71".to_string()],
            servers_ipv6: vec![
                "2001:67c:28a4::".to_string(),
                "2a01:3a0:53:53::".to_string(),
            ],
            doh_template: None,
            dot_hostname: None,
            supports_doh: false,
            supports_dot: false,
            icon: "🕵️".to_string(),
            color: "#6366f1".to_string(),
            website: Some("https://dnsprivacy.org".to_string()),
        },
        
        // Security DNS
        DnsPreset {
            id: "cloudflare-malware".to_string(),
            name: "Cloudflare (Malware)".to_string(),
            description: "Cloudflare DNS с блокировкой вредоносного ПО".to_string(),
            category: "security".to_string(),
            servers_ipv4: vec!["1.1.1.2".to_string(), "1.0.0.2".to_string()],
            servers_ipv6: vec![
                "2606:4700:4700::1112".to_string(),
                "2606:4700:4700::1002".to_string(),
            ],
            doh_template: Some("https://security.cloudflare-dns.com/dns-query".to_string()),
            dot_hostname: Some("security.cloudflare-dns.com".to_string()),
            supports_doh: true,
            supports_dot: true,
            icon: "🛡️".to_string(),
            color: "#10b981".to_string(),
            website: Some("https://1.1.1.1/family".to_string()),
        },
        DnsPreset {
            id: "quad9".to_string(),
            name: "Quad9".to_string(),
            description: "Безопасный DNS с блокировкой угроз".to_string(),
            category: "security".to_string(),
            servers_ipv4: vec!["9.9.9.9".to_string(), "149.112.112.112".to_string()],
            servers_ipv6: vec![
                "2620:fe::fe".to_string(),
                "2620:fe::9".to_string(),
            ],
            doh_template: Some("https://dns.quad9.net/dns-query".to_string()),
            dot_hostname: Some("dns.quad9.net".to_string()),
            supports_doh: true,
            supports_dot: true,
            icon: "🔒".to_string(),
            color: "#0d47a1".to_string(),
            website: Some("https://quad9.net".to_string()),
        },
        DnsPreset {
            id: "quad9-unsecured".to_string(),
            name: "Quad9 (Unsecured)".to_string(),
            description: "Quad9 без блокировки угроз".to_string(),
            category: "public".to_string(),
            servers_ipv4: vec!["9.9.9.10".to_string(), "149.112.112.10".to_string()],
            servers_ipv6: vec![
                "2620:fe::10".to_string(),
                "2620:fe::fe:10".to_string(),
            ],
            doh_template: Some("https://dns10.quad9.net/dns-query".to_string()),
            dot_hostname: Some("dns10.quad9.net".to_string()),
            supports_doh: true,
            supports_dot: true,
            icon: "🌐".to_string(),
            color: "#1976d2".to_string(),
            website: Some("https://quad9.net".to_string()),
        },
        DnsPreset {
            id: "yandex-safe".to_string(),
            name: "Яндекс.DNS Безопасный".to_string(),
            description: "Защита от вредоносных сайтов".to_string(),
            category: "security".to_string(),
            servers_ipv4: vec!["77.88.8.88".to_string(), "77.88.8.2".to_string()],
            servers_ipv6: vec![
                "2a02:6b8::feed:bad".to_string(),
                "2a02:6b8:0:1::feed:bad".to_string(),
            ],
            doh_template: None,
            dot_hostname: Some("safe.dot.dns.yandex.net".to_string()),
            supports_doh: false,
            supports_dot: true,
            icon: "🛡️".to_string(),
            color: "#fc3f1d".to_string(),
            website: Some("https://dns.yandex.ru".to_string()),
        },
        DnsPreset {
            id: "comodo".to_string(),
            name: "Comodo Secure DNS".to_string(),
            description: "DNS с защитой от фишинга".to_string(),
            category: "security".to_string(),
            servers_ipv4: vec!["8.26.56.26".to_string(), "8.20.247.20".to_string()],
            servers_ipv6: vec![],
            doh_template: None,
            dot_hostname: None,
            supports_doh: false,
            supports_dot: false,
            icon: "🔐".to_string(),
            color: "#10b981".to_string(),
            website: Some("https://www.comodo.com/secure-dns".to_string()),
        },
        DnsPreset {
            id: "cleanbrowsing-security".to_string(),
            name: "CleanBrowsing Security".to_string(),
            description: "Защита от вредоносных сайтов".to_string(),
            category: "security".to_string(),
            servers_ipv4: vec!["185.228.168.9".to_string(), "185.228.169.9".to_string()],
            servers_ipv6: vec![
                "2a0d:2a00:1::2".to_string(),
                "2a0d:2a00:2::2".to_string(),
            ],
            doh_template: Some("https://doh.cleanbrowsing.org/doh/security-filter/".to_string()),
            dot_hostname: Some("security-filter-dns.cleanbrowsing.org".to_string()),
            supports_doh: true,
            supports_dot: true,
            icon: "🛡️".to_string(),
            color: "#10b981".to_string(),
            website: Some("https://cleanbrowsing.org".to_string()),
        },
        
        // AdBlock DNS
        DnsPreset {
            id: "adguard".to_string(),
            name: "AdGuard DNS".to_string(),
            description: "Блокировка рекламы и трекеров".to_string(),
            category: "adblock".to_string(),
            servers_ipv4: vec!["94.140.14.14".to_string(), "94.140.15.15".to_string()],
            servers_ipv6: vec![
                "2a10:50c0::ad1:ff".to_string(),
                "2a10:50c0::ad2:ff".to_string(),
            ],
            doh_template: Some("https://dns.adguard-dns.com/dns-query".to_string()),
            dot_hostname: Some("dns.adguard-dns.com".to_string()),
            supports_doh: true,
            supports_dot: true,
            icon: "🚫".to_string(),
            color: "#ef4444".to_string(),
            website: Some("https://adguard-dns.io".to_string()),
        },
        DnsPreset {
            id: "adguard-unfiltered".to_string(),
            name: "AdGuard Unfiltered".to_string(),
            description: "AdGuard без фильтрации".to_string(),
            category: "public".to_string(),
            servers_ipv4: vec!["94.140.14.140".to_string(), "94.140.14.141".to_string()],
            servers_ipv6: vec![
                "2a10:50c0::1:ff".to_string(),
                "2a10:50c0::2:ff".to_string(),
            ],
            doh_template: Some("https://unfiltered.adguard-dns.com/dns-query".to_string()),
            dot_hostname: Some("unfiltered.adguard-dns.com".to_string()),
            supports_doh: true,
            supports_dot: true,
            icon: "🌐".to_string(),
            color: "#68bcff".to_string(),
            website: Some("https://adguard-dns.io".to_string()),
        },
        DnsPreset {
            id: "control-d-adblock".to_string(),
            name: "Control D AdBlock".to_string(),
            description: "DNS с блокировкой рекламы".to_string(),
            category: "adblock".to_string(),
            servers_ipv4: vec![
                "76.76.2.2".to_string(),
                "76.76.10.2".to_string(),
            ],
            servers_ipv6: vec![
                "2606:1a40::2".to_string(),
                "2606:1a40:1::2".to_string(),
            ],
            doh_template: Some("https://freedns.controld.com/p2".to_string()),
            dot_hostname: Some("p2.freedns.controld.com".to_string()),
            supports_doh: true,
            supports_dot: true,
            icon: "🚫".to_string(),
            color: "#ef4444".to_string(),
            website: Some("https://controld.com".to_string()),
        },
        DnsPreset {
            id: "dnsforge".to_string(),
            name: "DNS.Forge".to_string(),
            description: "Блокировка рекламы и вредоносов".to_string(),
            category: "adblock".to_string(),
            servers_ipv4: vec!["176.9.93.198".to_string(), "176.9.1.117".to_string()],
            servers_ipv6: vec![
                "2a01:4f8:151:34aa::198".to_string(),
                "2a01:4f8:141:316d::117".to_string(),
            ],
            doh_template: Some("https://dnsforge.de/dns-query".to_string()),
            dot_hostname: Some("dnsforge.de".to_string()),
            supports_doh: true,
            supports_dot: true,
            icon: "🚫".to_string(),
            color: "#ef4444".to_string(),
            website: Some("https://dnsforge.de".to_string()),
        },
        
        // Family DNS
        DnsPreset {
            id: "cloudflare-family".to_string(),
            name: "Cloudflare (Family)".to_string(),
            description: "Cloudflare DNS с защитой для семьи".to_string(),
            category: "family".to_string(),
            servers_ipv4: vec!["1.1.1.3".to_string(), "1.0.0.3".to_string()],
            servers_ipv6: vec![
                "2606:4700:4700::1113".to_string(),
                "2606:4700:4700::1003".to_string(),
            ],
            doh_template: Some("https://family.cloudflare-dns.com/dns-query".to_string()),
            dot_hostname: Some("family.cloudflare-dns.com".to_string()),
            supports_doh: true,
            supports_dot: true,
            icon: "👨‍👩‍👧‍👦".to_string(),
            color: "#f59e0b".to_string(),
            website: Some("https://1.1.1.1/family".to_string()),
        },
        DnsPreset {
            id: "adguard-family".to_string(),
            name: "AdGuard Family".to_string(),
            description: "AdGuard с защитой для семьи".to_string(),
            category: "family".to_string(),
            servers_ipv4: vec!["94.140.14.15".to_string(), "94.140.15.16".to_string()],
            servers_ipv6: vec![
                "2a10:50c0::bad1:ff".to_string(),
                "2a10:50c0::bad2:ff".to_string(),
            ],
            doh_template: Some("https://family.adguard-dns.com/dns-query".to_string()),
            dot_hostname: Some("family.adguard-dns.com".to_string()),
            supports_doh: true,
            supports_dot: true,
            icon: "👪".to_string(),
            color: "#f59e0b".to_string(),
            website: Some("https://adguard-dns.io".to_string()),
        },
        DnsPreset {
            id: "yandex-family".to_string(),
            name: "Яндекс.DNS Семейный".to_string(),
            description: "Защита для всей семьи".to_string(),
            category: "family".to_string(),
            servers_ipv4: vec!["77.88.8.7".to_string(), "77.88.8.3".to_string()],
            servers_ipv6: vec![
                "2a02:6b8::feed:a11".to_string(),
                "2a02:6b8:0:1::feed:a11".to_string(),
            ],
            doh_template: None,
            dot_hostname: Some("family.dot.dns.yandex.net".to_string()),
            supports_doh: false,
            supports_dot: true,
            icon: "👨‍👩‍👧".to_string(),
            color: "#fc3f1d".to_string(),
            website: Some("https://dns.yandex.ru".to_string()),
        },
        DnsPreset {
            id: "cleanbrowsing-family".to_string(),
            name: "CleanBrowsing Family".to_string(),
            description: "Защита для всей семьи от нежелательного контента".to_string(),
            category: "family".to_string(),
            servers_ipv4: vec!["185.228.168.168".to_string(), "185.228.169.168".to_string()],
            servers_ipv6: vec![
                "2a0d:2a00:1::".to_string(),
                "2a0d:2a00:2::".to_string(),
            ],
            doh_template: Some("https://doh.cleanbrowsing.org/doh/family-filter/".to_string()),
            dot_hostname: Some("family-filter-dns.cleanbrowsing.org".to_string()),
            supports_doh: true,
            supports_dot: true,
            icon: "👨‍👩‍👧‍👦".to_string(),
            color: "#f59e0b".to_string(),
            website: Some("https://cleanbrowsing.org".to_string()),
        },
        DnsPreset {
            id: "cleanbrowsing-adult".to_string(),
            name: "CleanBrowsing Adult".to_string(),
            description: "Блокировка контента для взрослых".to_string(),
            category: "family".to_string(),
            servers_ipv4: vec!["185.228.168.10".to_string(), "185.228.169.11".to_string()],
            servers_ipv6: vec![
                "2a0d:2a00:1::1".to_string(),
                "2a0d:2a00:2::1".to_string(),
            ],
            doh_template: Some("https://doh.cleanbrowsing.org/doh/adult-filter/".to_string()),
            dot_hostname: Some("adult-filter-dns.cleanbrowsing.org".to_string()),
            supports_doh: true,
            supports_dot: true,
            icon: "🔞".to_string(),
            color: "#dc2626".to_string(),
            website: Some("https://cleanbrowsing.org".to_string()),
        },
        
        // Russian DNS
        DnsPreset {
            id: "rostelecom".to_string(),
            name: "Ростелеком DNS".to_string(),
            description: "DNS от Ростелеком".to_string(),
            category: "public".to_string(),
            servers_ipv4: vec!["213.158.0.6".to_string(), "213.158.0.7".to_string()],
            servers_ipv6: vec![],
            doh_template: None,
            dot_hostname: None,
            supports_doh: false,
            supports_dot: false,
            icon: "🇷🇺".to_string(),
            color: "#0056b8".to_string(),
            website: Some("https://www.company.rt.ru".to_string()),
        },
        
        // Specialized DNS
        DnsPreset {
            id: "dns-sb".to_string(),
            name: "DNS.SB".to_string(),
            description: "Быстрый DNS с фокусом на приватность".to_string(),
            category: "privacy".to_string(),
            servers_ipv4: vec!["185.222.222.222".to_string(), "45.11.45.11".to_string()],
            servers_ipv6: vec![
                "2a09::".to_string(),
                "2a11::".to_string(),
            ],
            doh_template: Some("https://doh.dns.sb/dns-query".to_string()),
            dot_hostname: Some("dot.dns.sb".to_string()),
            supports_doh: true,
            supports_dot: true,
            icon: "🔒".to_string(),
            color: "#3b82f6".to_string(),
            website: Some("https://dns.sb".to_string()),
        },
        DnsPreset {
            id: "libredns".to_string(),
            name: "LibreDNS".to_string(),
            description: "Свободный DNS без логирования".to_string(),
            category: "privacy".to_string(),
            servers_ipv4: vec!["116.202.176.26".to_string()],
            servers_ipv6: vec![],
            doh_template: Some("https://doh.libredns.gr/dns-query".to_string()),
            dot_hostname: Some("dot.libredns.gr".to_string()),
            supports_doh: true,
            supports_dot: true,
            icon: "🆓".to_string(),
            color: "#8b5cf6".to_string(),
            website: Some("https://libredns.gr".to_string()),
        },
        DnsPreset {
            id: "switch-ch".to_string(),
            name: "SWITCH DNS".to_string(),
            description: "DNS от швейцарской исследовательской сети".to_string(),
            category: "public".to_string(),
            servers_ipv4: vec!["130.59.31.248".to_string(), "130.59.31.251".to_string()],
            servers_ipv6: vec![
                "2001:620:0:ff::2".to_string(),
                "2001:620:0:ff::3".to_string(),
            ],
            doh_template: None,
            dot_hostname: None,
            supports_doh: false,
            supports_dot: false,
            icon: "🇨🇭".to_string(),
            color: "#dc2626".to_string(),
            website: Some("https://www.switch.ch".to_string()),
        },
    ]
}

pub fn get_preset_by_id(id: &str) -> Option<DnsPreset> {
    get_default_presets().into_iter().find(|p| p.id == id)
}